-- ----------------------------------------------
-- DDL Statements for schemas
-- ----------------------------------------------

CREATE SCHEMA "OBJPROG";

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "OBJPROG"."PERSONEN" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "FAMILIENAAM" VARCHAR(255), "VOORNAAM" VARCHAR(255));

CREATE TABLE "OBJPROG"."CONTACTGEGEVENS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "P_ID" INTEGER, "CODE" CHAR(1), "ADRES" VARCHAR(255));

CREATE TABLE "OBJPROG"."CONTACTCODES" ("ID" CHAR(1) NOT NULL, "NAAM" VARCHAR(255));

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- PRIMARY/UNIQUE
ALTER TABLE "OBJPROG"."CONTACTCODES" ADD CONSTRAINT "SQL0000000001-286cc01e-0196-aab0-217c-00001e556608" PRIMARY KEY ("ID");

ALTER TABLE "OBJPROG"."CONTACTGEGEVENS" ADD CONSTRAINT "SQL0000000005-832a0051-0196-ac63-0382-00001e554a38" PRIMARY KEY ("ID");

ALTER TABLE "OBJPROG"."PERSONEN" ADD CONSTRAINT "SQL0000000000-582f8014-0196-ac63-0382-00001e554a38" PRIMARY KEY ("ID");

-- FOREIGN
ALTER TABLE "OBJPROG"."CONTACTGEGEVENS" ADD CONSTRAINT "FK_CONTACTCODES" FOREIGN KEY ("CODE") REFERENCES "OBJPROG"."CONTACTCODES" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "OBJPROG"."CONTACTGEGEVENS" ADD CONSTRAINT "FK_PERSONEN" FOREIGN KEY ("P_ID") REFERENCES "OBJPROG"."PERSONEN" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;